#!/bin/zsh

## Main function set
# Class --Autosource

enter() {
   arch-chroot /mnt
}

function \
bootstrap() {
   unset target

   echo "Target? :$target"
   read target

   pacstrap $target base base-devel nano linux-firmware linux linux-headers linux-zen linux-zen-headers amd-ucode intel-ucode \
   zsh zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search \
   sof-firmware sof-tools alsa-firmware alsa-utils alsa-card-profiles \
   grub os-prober efibootmgr mkinitcpio initramfs \
   fuse iwd iw dhcpcd networkmanager network-manager-applet \
   arch-install-scripts bashtop htop bluez bluez-tools bluez-utils mesa reflector \
   plasma plasma-desktop plasma-sdk konsole terminator dolphin gimp inkscape \
   git wget github-cli doctl \
   qemu libvirt virtualbox x11vnc \
   docker docker-scan docker-buildx docker-compose lxd lxc \
   plasma plasma-sdk plasma-desktop konsole terminator dolphin kate kwrite tmux \
   lightdm lightdm-gtk-greeter plasma-wayland-protocols plasma-wayland-session xfce4 xfce4-goodies \
   iw iwd dhcpcd \
   composer yarn npm \
   bash-language-server python-lsp-server kdevelop kdevelop-php kdevelop-python typescript-language-server \
   typescript go rust nodejs code tidy cgrep hound go-bindata pylama \
   ruby ruby-rspec shellcheck lua-language-server python-typer python-fastapi vscode-json-languageserver argbash

}

function install_it() {

genfstab -U /mnt >/mnt/etc/fstab

arch-chroot /mnt echo "foreach items in /main/source-docs/*; 
do
source $items
done" >/mnt/root/.zshrc

arch-chroot /mnt zsh

}



