#!/bin/zsh

## Main function set
# Class --Autosource

enter() {
   arch-chroot /mnt
}

function \
bootstrap() {
   pacstrap /mnt base base-devel nano linux-firmware linux linux-headers linux-zen linux-zen-headers zsh zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search sof-firmware sof-tools alsa-firmware alsa-utils grub os-prober efibootmgr mkinitcpio initramfs fuse iwd iw dhcpcd arch-install-scripts bashtop htop bluez bluez-tools bluez-utils mesa reflector plasma plasma-desktop plasma-sdk konsole terminator dolphin gimp inkscape git wget github-cli grub

}

function install_it() {

genfstab -U /mnt >/mnt/etc/fstab

arch-chroot /mnt echo "foreach items in /main/source-docs/*; 
do
source $items
done" >/mnt/root/.zshrc

arch-chroot /mnt zsh

}



