#!/usr/bin/env zsh

## Description: Script
## Class: General
## Licence: GLL / GLS
## Scriptor: ZSH
## Type: Shell


virt-actions() {
	setopt extendedglob


	foreach fu in /main/source-docs/*; do
        source $fu
				if [[ $alias = /main/source-docs/.alias ]]; then
					source $alias
				fi
    done
}

